apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pod
  template:   # for pod definition
    metadata:
      labels:
        app: postgres-pod
    spec:
      containers:
      - name: database
        image: postgres
        ports:
        - containerPort: 5432
        env:
        # Define the environment variable
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: postgres-cm
              # Specify the key associated with the value
              key: POSTGRES_USER        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: postgres-secret
              # Specify the key associated with the value
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST_AUTH_METHOD
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: postgres-cm
              # Specify the key associated with the value
              key: POSTGRES_HOST_AUTH_METHOD
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          # pointer to the configuration of HOW we want the mount to be implemented
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres-pod
  ports:
  - port: 5432
    targetPort: 5432
