apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resultApp.appName}}
  labels:
    name: result-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-pod
  template:   # for pod definition
    metadata:
      name: result-app-pod
      labels:
        app: result-pod
    spec:
      containers:
      - name: result-app
        image: {{ .Values.resultApp.image}}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: result-nodeport
spec:
  type: NodePort
  selector:
    app: {{ .Values.resultService.appName}}
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
