apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.appName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.worker.appName}}
  template:   # for pod definition
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.worker.image}}

